import { DataRequest, Model } from "../../models/models";
import { ApiClientV3Provider } from "../api-client/api-client.v3";

export class ConfigurationProvider {
    api: ApiClientV3Provider;

    findConfigurations(
        _configuration: DataRequest.GetConfiguration
    ): Promise<Array<Model.Configuration>> {
        let config: Array<Model.Configuration> = [
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "EMPAQUE_DAÑADO",
                paramCaption: "EMPAQUE DAÑADO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Productos con el empaque dañado",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "SI",
                decimalValue: 0,
                spare3: "",
                spare4: "",
                spare5: "",
                color: "-65536"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_DEFAULT",
                paramCaption: "DEFAULT",
                numericValue: 1,
                moneyValue: 0,
                textValue:
                    "Estado DEFAULT que tiene que existir siempre en la BD",
                dateValue: null,
                rangeNumStart: 1,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "0",
                spare2: "SI",
                decimalValue: 0,
                spare3: "",
                spare4: "",
                spare5: "",
                color: "-64"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_MANCHADO",
                paramCaption: "MACHADO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Materiales Manchados",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "SI",
                decimalValue: 0,
                spare3: "B01ANX-P01-F01-NU",
                spare4: "",
                spare5: "",
                color: "-13395457"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_MATERIAL_NO_PREPARADO",
                paramCaption: "MATERIAL NO PREPARADO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Material que no esta listo",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "NO",
                decimalValue: 0,
                spare3: "B01ANX-P01-F01-NU",
                spare4: "",
                spare5: "",
                color: "-7667712"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_MOJADO",
                paramCaption: "MOJADO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Materiales Mojados ",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "SI",
                decimalValue: 0,
                spare3: "B03-R01-C01-NA",
                spare4: "",
                spare5: "",
                color: "-16776961"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_prueba",
                paramCaption: "prueba2",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Material que no esta listo",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "NO",
                decimalValue: 0,
                spare3: "B01ANX-P01-F01-NU",
                spare4: "",
                spare5: "",
                color: "-7667712"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_prueba2",
                paramCaption: "prueba2",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Material que no esta listo",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "NO",
                decimalValue: 0,
                spare3: "B01ANX-P01-F01-NU",
                spare4: "",
                spare5: "",
                color: "-7667712"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "ESTADO_QUEBRADO",
                paramCaption: "QUEBRADO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Materiales Quebrados",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "SI",
                decimalValue: 0,
                spare3: "KK",
                spare4: "",
                spare5: "",
                color: "-65536"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "INCOMPLETO",
                paramCaption: "INCOMPLETO",
                numericValue: 0,
                moneyValue: 0,
                textValue: "Materiales incompletos",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "0",
                spare2: "SI",
                decimalValue: 0,
                spare3: "B01ANX-P01-F01-NU",
                spare4: "",
                spare5: "",
                color: "-16711681"
            },
            {
                paramType: "ESTADO",
                paramGroup: "ESTADOS",
                paramGroupCaption: "Estados",
                paramName: "MAL_ETIQUETADO",
                paramCaption: "MAL ETIQUETADO",
                numericValue: 0,
                moneyValue: 0,
                textValue:
                    "Productos que tienen mala la información de la etiqueta que los identifica",
                dateValue: null,
                rangeNumStart: 0,
                rangeNumEnd: 0,
                rangeDateStart: null,
                rangeDateEnd: null,
                spare1: "1",
                spare2: "NO",
                decimalValue: 0,
                spare3: "B07-R02-C01-NA",
                spare4: "",
                spare5: "",
                color: "-13395457"
            }
        ];
        return Promise.resolve(config);
    }
}
